In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [48]:
cd /home/abhishek/Downloads/P16-Artificial-Neural-Networks/Artificial_Neural_Networks


/home/abhishek/Downloads/P16-Artificial-Neural-Networks/Artificial_Neural_Networks


In [78]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [50]:
x=dataset.iloc[:,3:13].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [51]:
y=dataset.iloc[:,13].values
y

array([1, 0, 1, ..., 1, 1, 0])

In [52]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label_encoder_x1=LabelEncoder()
x[:,1]=label_encoder_x1.fit_transform(x[:,1])
x[:,1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [53]:
label_encoder_x2=LabelEncoder()
x[:,2]=label_encoder_x2.fit_transform(x[:,2])
x[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [54]:
onehotencoder=OneHotEncoder(categorical_features=[1])
x=onehotencoder.fit_transform(x).toarray()
x=x[:,1:]
x

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
x_train

array([[0.0000000e+00, 0.0000000e+00, 6.4100000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 5.5796830e+04],
       [0.0000000e+00, 0.0000000e+00, 5.4100000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.9823020e+04],
       [0.0000000e+00, 0.0000000e+00, 5.9000000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.3848580e+04],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.3800000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8142987e+05],
       [0.0000000e+00, 1.0000000e+00, 5.9000000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.4875016e+05],
       [1.0000000e+00, 0.0000000e+00, 6.2300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1885526e+05]])

In [56]:
len(x_train)

7000

In [57]:
len(x_test)

3000

# scaling it is very import for creating a Artificial Neural Network(ANN) and it's compulsory.....

In [58]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [59]:
x_train

array([[-0.56987189, -0.5731713 , -0.09792126, ...,  0.64198477,
         0.96683535, -0.76862426],
       [-0.56987189, -0.5731713 , -1.12612023, ...,  0.64198477,
        -1.03430227, -1.39359887],
       [-0.56987189, -0.5731713 , -0.62230274, ..., -1.55766936,
         0.96683535, -1.49739308],
       ...,
       [-0.56987189, -0.5731713 ,  0.89943174, ...,  0.64198477,
        -1.03430227,  1.41400417],
       [-0.56987189,  1.74467913, -0.62230274, ...,  0.64198477,
         0.96683535,  0.84625811],
       [ 1.75478035, -0.5731713 , -0.28299708, ...,  0.64198477,
        -1.03430227,  0.32689267]])

In [60]:
x_test

array([[ 1.66826321, -0.57529746, -0.56233235, ...,  0.65569297,
         0.97823676,  1.61444413],
       [-0.59942579, -0.57529746, -1.33954221, ...,  0.65569297,
        -1.02224741,  0.496527  ],
       [-0.59942579,  1.7382312 ,  0.58247678, ...,  0.65569297,
         0.97823676, -0.4265498 ],
       ...,
       [-0.59942579, -0.57529746,  0.36191723, ...,  0.65569297,
         0.97823676,  1.17089933],
       [-0.59942579, -0.57529746,  0.43543708, ...,  0.65569297,
         0.97823676, -0.51163936],
       [ 1.66826321, -0.57529746,  0.84504769, ...,  0.65569297,
         0.97823676, -1.15798768]])

In [61]:
import keras as kr
print(kr.__version__)


2.2.4


# cretaing an Artiicial Neural Network....with the help of keras...

In [62]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [63]:
#for initializing the ANN
classifier=Sequential()

In [64]:
#Adding the input layes in ANN
classifier.add(Dense(activation='relu',units=6,kernel_initializer='uniform',input_dim=11))
#outpur_dim=(average of dependent and inpendent varibales...)
#input_dim=(the total number of independent variables...)
#activation is the function which we are using for optimizing....relu for rectifier..
#init is the  defining the that how the data is distributed...
#adding the one more layer
classifier.add(Dense(activation='relu',units=6,kernel_initializer='uniform'))
#No need to add the  input layer...because we  have added before the input layer 
#finally going to add final layer or output layer
classifier.add(Dense(activation='sigmoid',units=1,kernel_initializer='uniform'))

In [65]:
#compliling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#adam->  it is the best optimizer method in stochastic process
#binary_crossentropy->  it is loss function for binary dependent variables
#metics->  it will show the accuracy of of the artificual neueal network...

In [66]:
#now we will fit the our test dataset in the ANN
classifier.fit(x_train,y_train,batch_size=10,epochs=10) 
#nb_epoch->  it is a type of iterations  and it will show the accuracy


Epoch 1/10
7000/7000 [==============================] - 11s 2ms/step - loss: 0.6196 - acc: 0.7976
Epoch 2/10
7000/7000 [==============================] - 7s 1ms/step - loss: 0.5214 - acc: 0.8194
Epoch 3/10
7000/7000 [==============================] - 7s 1ms/step - loss: 0.4818 - acc: 0.8206
Epoch 4/10
7000/7000 [==============================] - 7s 974us/step - loss: 0.4685 - acc: 0.8214
Epoch 5/10
7000/7000 [==============================] - 8s 1ms/step - loss: 0.4639 - acc: 0.8233
Epoch 6/10
7000/7000 [==============================] - 8s 1ms/step - loss: 0.4621 - acc: 0.8240
Epoch 7/10
7000/7000 [==============================] - 7s 993us/step - loss: 0.4617 - acc: 0.8239
Epoch 8/10
7000/7000 [==============================] - 7s 1ms/step - loss: 0.4609 - acc: 0.8243
Epoch 9/10
7000/7000 [==============================] - 8s 1ms/step - loss: 0.4609 - acc: 0.8244
Epoch 10/10
7000/7000 [==============================] - 8s 1ms/step - loss: 0.4608 - acc: 0.8249


In [81]:
y_predicted=pd.DataFrame(classifier.predict(x_test))
y_predicted.columns=['y_predicted']
y_predicted.head(10)

y_predicted
0     0.175136
1     0.175136
2     0.175136
3     0.175136
4     0.175136
5     0.946332
6     0.175136
7     0.175136
8     0.175136
9     0.948168

In [82]:
y_predicted2=pd.DataFrame((y_predicted>0.5))
y_predicted2.columns=['y_predicted2']
y_predicted2.head(10)


y_predicted2
0         False
1         False
2         False
3         False
4         False
5          True
6         False
7         False
8         False
9          True