In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
cd /home/abhishek/Downloads/P16-Artificial-Neural-Networks/Artificial_Neural_Networks


/home/abhishek/Downloads/P16-Artificial-Neural-Networks/Artificial_Neural_Networks


In [3]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [4]:
x=dataset.iloc[:,3:13].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y=dataset.iloc[:,13].values
y

array([1, 0, 1, ..., 1, 1, 0])

In [6]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label_encoder_x1=LabelEncoder()
x[:,1]=label_encoder_x1.fit_transform(x[:,1])
x[:,1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [7]:
label_encoder_x2=LabelEncoder()
x[:,2]=label_encoder_x2.fit_transform(x[:,2])
x[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [8]:
onehotencoder=OneHotEncoder(categorical_features=[1])
x=onehotencoder.fit_transform(x).toarray()
x=x[:,1:]
x

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
x_train

array([[0.0000000e+00, 0.0000000e+00, 6.4100000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 5.5796830e+04],
       [0.0000000e+00, 0.0000000e+00, 5.4100000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.9823020e+04],
       [0.0000000e+00, 0.0000000e+00, 5.9000000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.3848580e+04],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.3800000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8142987e+05],
       [0.0000000e+00, 1.0000000e+00, 5.9000000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.4875016e+05],
       [1.0000000e+00, 0.0000000e+00, 6.2300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1885526e+05]])

In [10]:
len(x_train)

7000

In [11]:
len(x_test)

3000

# scaling it is very import for creating a Artificial Neural Network(ANN) and it's compulsory.....

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [13]:
x_train

array([[-0.56987189, -0.5731713 , -0.09792126, ...,  0.64198477,
         0.96683535, -0.76862426],
       [-0.56987189, -0.5731713 , -1.12612023, ...,  0.64198477,
        -1.03430227, -1.39359887],
       [-0.56987189, -0.5731713 , -0.62230274, ..., -1.55766936,
         0.96683535, -1.49739308],
       ...,
       [-0.56987189, -0.5731713 ,  0.89943174, ...,  0.64198477,
        -1.03430227,  1.41400417],
       [-0.56987189,  1.74467913, -0.62230274, ...,  0.64198477,
         0.96683535,  0.84625811],
       [ 1.75478035, -0.5731713 , -0.28299708, ...,  0.64198477,
        -1.03430227,  0.32689267]])

In [14]:
x_test

array([[ 1.66826321, -0.57529746, -0.56233235, ...,  0.65569297,
         0.97823676,  1.61444413],
       [-0.59942579, -0.57529746, -1.33954221, ...,  0.65569297,
        -1.02224741,  0.496527  ],
       [-0.59942579,  1.7382312 ,  0.58247678, ...,  0.65569297,
         0.97823676, -0.4265498 ],
       ...,
       [-0.59942579, -0.57529746,  0.36191723, ...,  0.65569297,
         0.97823676,  1.17089933],
       [-0.59942579, -0.57529746,  0.43543708, ...,  0.65569297,
         0.97823676, -0.51163936],
       [ 1.66826321, -0.57529746,  0.84504769, ...,  0.65569297,
         0.97823676, -1.15798768]])

In [15]:
import keras as kr
print(kr.__version__)


/home/abhishek/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


2.2.4


# cretaing an Artiicial Neural Network....with the help of keras...

In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
#for initializing the ANN
classifier=Sequential()

In [ ]:
#Adding the input layes in ANN
classifier.add(Dense(activation='relu',units=6,kernel_initializer='uniform',input_dim=11))
#outpur_dim=(average of dependent and inpendent varibales...)
#input_dim=(the total number of independent variables...)
#activation is the function which we are using for optimizing....relu for rectifier..
#init is the  defining the that how the data is distributed...
#adding the one more layer
classifier.add(Dense(activation='relu',units=6,kernel_initializer='uniform'))
#No need to add the  input layer...because we  have added before the input layer 
#finally going to add final layer or output layer
classifier.add(Dense(activation='sigmoid',units=1,kernel_initializer='uniform'))

In [ ]:
#compliling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#adam->  it is the best optimizer method in stochastic process
#binary_crossentropy->  it is loss function for binary dependent variables
#metics->  it will show the accuracy of of the artificual neueal network...

In [ ]:
#now we will fit the our test dataset in the ANN
classifier.fit(x_train,y_train,batch_size=10,epochs=10) 
#nb_epoch->  it is a type of iterations  and it will show the accuracy


In [ ]:
y_predicted=pd.DataFrame(classifier.predict(x_test))
y_predicted.columns=['y_predicted']
y_predicted.head(10)

In [ ]:
y_predicted2=pd.DataFrame((y_predicted>0.5))
y_predicted2.columns=['y_predicted2']
y_predicted2.head(10)


In [23]:
# using kfold validation for getting better acuuracies
# we split the datatset into 10 parts  and and test each one
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [24]:
def build_classifier():
    classifier=Sequential()
    classifier.add(Dense(activation='relu',units=6,kernel_initializer='uniform',input_dim=11))
    classifier.add(Dense(activation='relu',units=6,kernel_initializer='uniform'))
    classifier.add(Dense(activation='sigmoid',units=1,kernel_initializer='uniform'))
    classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return classifier


In [ ]:
classifier=KerasClassifier(build_fn=build_classifier,batch_size=10,epochs=10)
accuracies=cross_val_score(estimator=classifier,X=x_train,y=y_train,cv=10,n_jobs=-1)

Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10


In [20]:
#Tunning the ANN
from keras.wrappers.scikit_learn import KerasClassifier
#wrapping the keras and scikit_learn together
from sklearn.model_selection import GridSearchCV
#GridSearchCV will calculate the accuracy with more than one optimizer,parameters and all others....

In [26]:
def build_classifier(optimizer):
    classifier=Sequential()
    classifier.add(Dense(activation='relu',units=6,kernel_initializer='uniform',input_dim=11))
    classifier.add(Dense(activation='relu',units=6,kernel_initializer='uniform'))
    classifier.add(Dense(activation='sigmoid',units=1,kernel_initializer='uniform'))
    classifier.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
    return classifier

In [27]:
classifier=KerasClassifier(build_fn=build_classifier)
parameters={'batch_size':[25,32],
           'epochs':[10,20],
           'optimizer':['adam','rmsprop']
}
#making a dictionary of parameters wichi is conatinig batch_size,different epochs and optimizers....

In [30]:
grid_search=GridSearchCV(estimator=classifier,
                        param_grid=parameters,
                        scoring='accuracy',
                        cv=10)

In [31]:
grid_search=grid_search.fit(x_train,y_train)

Epoch 1/10
6300/6300 [==============================] - 9s 1ms/step - loss: 0.5871 - acc: 0.7973
Epoch 2/10
6300/6300 [==============================] - 3s 461us/step - loss: 0.4305 - acc: 0.8033
Epoch 3/10
6300/6300 [==============================] - 3s 482us/step - loss: 0.4130 - acc: 0.8219
Epoch 4/10
6300/6300 [==============================] - 4s 570us/step - loss: 0.4046 - acc: 0.8240
Epoch 5/10
6300/6300 [==============================] - 3s 473us/step - loss: 0.3986 - acc: 0.8281
Epoch 6/10
6300/6300 [==============================] - 3s 536us/step - loss: 0.3937 - acc: 0.8283
Epoch 7/10
6300/6300 [==============================] - 3s 441us/step - loss: 0.3902 - acc: 0.8283
Epoch 8/10
6300/6300 [==============================] - 3s 545us/step - loss: 0.3870 - acc: 0.8311
Epoch 9/10
6300/6300 [==============================] - 3s 425us/step - loss: 0.3829 - acc: 0.8311
Epoch 10/10
6300/6300 [==============================] - 3s 515us/step - loss: 0.3792 - acc: 0.8322
Epoch 1/10


6300/6300 [==============================] - 3s 430us/step - loss: 0.4294 - acc: 0.7976
Epoch 4/10
6300/6300 [==============================] - 3s 463us/step - loss: 0.4278 - acc: 0.7976
Epoch 5/10
6300/6300 [==============================] - 3s 444us/step - loss: 0.4264 - acc: 0.7976
Epoch 6/10
6300/6300 [==============================] - 3s 472us/step - loss: 0.4250 - acc: 0.7976
Epoch 7/10
6300/6300 [==============================] - 3s 429us/step - loss: 0.4237 - acc: 0.7976
Epoch 8/10
6300/6300 [==============================] - 3s 468us/step - loss: 0.4225 - acc: 0.7976
Epoch 9/10
6300/6300 [==============================] - 3s 435us/step - loss: 0.4205 - acc: 0.8046
Epoch 10/10
6300/6300 [==============================] - 3s 431us/step - loss: 0.4190 - acc: 0.8189
Epoch 1/10
6300/6300 [==============================] - 7s 1ms/step - loss: 0.5773 - acc: 0.7949
Epoch 2/10
6300/6300 [==============================] - 3s 487us/step - loss: 0.4390 - acc: 0.7973
Epoch 3/10
6300/6300 [

6300/6300 [==============================] - 2s 365us/step - loss: 0.4227 - acc: 0.8000
Epoch 6/10
6300/6300 [==============================] - 3s 464us/step - loss: 0.4194 - acc: 0.8000
Epoch 7/10
6300/6300 [==============================] - 3s 411us/step - loss: 0.4164 - acc: 0.8083
Epoch 8/10
6300/6300 [==============================] - 3s 456us/step - loss: 0.4136 - acc: 0.8265
Epoch 9/10
6300/6300 [==============================] - 3s 422us/step - loss: 0.4112 - acc: 0.8324
Epoch 10/10
6300/6300 [==============================] - 2s 381us/step - loss: 0.4094 - acc: 0.8329
Epoch 1/10
6300/6300 [==============================] - 7s 1ms/step - loss: 0.6350 - acc: 0.7954
Epoch 2/10
6300/6300 [==============================] - 3s 484us/step - loss: 0.4883 - acc: 0.7976
Epoch 3/10
6300/6300 [==============================] - 3s 441us/step - loss: 0.4411 - acc: 0.7976
Epoch 4/10
6300/6300 [==============================] - 3s 426us/step - loss: 0.4321 - acc: 0.7976
Epoch 5/10
6300/6300 [

6300/6300 [==============================] - 3s 536us/step - loss: 0.4193 - acc: 0.7997
Epoch 8/20
6300/6300 [==============================] - 3s 494us/step - loss: 0.4172 - acc: 0.7997
Epoch 9/20
6300/6300 [==============================] - 3s 534us/step - loss: 0.4153 - acc: 0.8171
Epoch 10/20
6300/6300 [==============================] - 3s 454us/step - loss: 0.4140 - acc: 0.8235
Epoch 11/20
6300/6300 [==============================] - 3s 509us/step - loss: 0.4125 - acc: 0.8262
Epoch 12/20
6300/6300 [==============================] - 3s 438us/step - loss: 0.4116 - acc: 0.8263
Epoch 13/20
6300/6300 [==============================] - 3s 474us/step - loss: 0.4105 - acc: 0.8278
Epoch 14/20
6300/6300 [==============================] - 3s 466us/step - loss: 0.4098 - acc: 0.8290
Epoch 15/20
6300/6300 [==============================] - 3s 522us/step - loss: 0.4092 - acc: 0.8302
Epoch 16/20
6300/6300 [==============================] - 3s 412us/step - loss: 0.4082 - acc: 0.8303
Epoch 17/20
63

6300/6300 [==============================] - 4s 573us/step - loss: 0.4133 - acc: 0.8259
Epoch 10/20
6300/6300 [==============================] - 3s 476us/step - loss: 0.4126 - acc: 0.8286
Epoch 11/20
6300/6300 [==============================] - 3s 530us/step - loss: 0.4112 - acc: 0.8300
Epoch 12/20
6300/6300 [==============================] - 3s 477us/step - loss: 0.4105 - acc: 0.8302
Epoch 13/20
6300/6300 [==============================] - 3s 464us/step - loss: 0.4101 - acc: 0.8310
Epoch 14/20
6300/6300 [==============================] - 3s 448us/step - loss: 0.4094 - acc: 0.8313
Epoch 15/20
6300/6300 [==============================] - 3s 447us/step - loss: 0.4087 - acc: 0.8310
Epoch 16/20
6300/6300 [==============================] - 3s 420us/step - loss: 0.4084 - acc: 0.8333
Epoch 17/20
6300/6300 [==============================] - 3s 495us/step - loss: 0.4079 - acc: 0.8333
Epoch 18/20
6300/6300 [==============================] - 3s 452us/step - loss: 0.4073 - acc: 0.8329
Epoch 19/20


6300/6300 [==============================] - 3s 481us/step - loss: 0.4134 - acc: 0.8273
Epoch 12/20
6300/6300 [==============================] - 3s 463us/step - loss: 0.4125 - acc: 0.8308
Epoch 13/20
6300/6300 [==============================] - 3s 490us/step - loss: 0.4114 - acc: 0.8321
Epoch 14/20
6300/6300 [==============================] - 3s 462us/step - loss: 0.4106 - acc: 0.8306
Epoch 15/20
6300/6300 [==============================] - 3s 446us/step - loss: 0.4100 - acc: 0.8325
Epoch 16/20
6300/6300 [==============================] - 3s 460us/step - loss: 0.4093 - acc: 0.8343
Epoch 17/20
6300/6300 [==============================] - 3s 505us/step - loss: 0.4089 - acc: 0.8341
Epoch 18/20
6300/6300 [==============================] - 3s 435us/step - loss: 0.4083 - acc: 0.8344
Epoch 19/20
6300/6300 [==============================] - 3s 490us/step - loss: 0.4080 - acc: 0.8343
Epoch 20/20
6300/6300 [==============================] - 3s 516us/step - loss: 0.4076 - acc: 0.8348
Epoch 1/20
6

6300/6300 [==============================] - 3s 544us/step - loss: 0.4113 - acc: 0.8311
Epoch 14/20
6300/6300 [==============================] - 3s 446us/step - loss: 0.4103 - acc: 0.8308
Epoch 15/20
6300/6300 [==============================] - 3s 478us/step - loss: 0.4095 - acc: 0.8333
Epoch 16/20
6300/6300 [==============================] - 3s 511us/step - loss: 0.4084 - acc: 0.8340
Epoch 17/20
6300/6300 [==============================] - 3s 496us/step - loss: 0.4076 - acc: 0.8341
Epoch 18/20
6300/6300 [==============================] - 3s 547us/step - loss: 0.4068 - acc: 0.8324
Epoch 19/20
6300/6300 [==============================] - 3s 488us/step - loss: 0.4062 - acc: 0.8333
Epoch 20/20
6300/6300 [==============================] - 3s 550us/step - loss: 0.4055 - acc: 0.8357
Epoch 1/20
6300/6300 [==============================] - 8s 1ms/step - loss: 0.5709 - acc: 0.7995
Epoch 2/20
6300/6300 [==============================] - 3s 512us/step - loss: 0.4418 - acc: 0.7995
Epoch 3/20
6300/

6300/6300 [==============================] - 3s 539us/step - loss: 0.3502 - acc: 0.8595
Epoch 16/20
6300/6300 [==============================] - 3s 508us/step - loss: 0.3490 - acc: 0.8598
Epoch 17/20
6300/6300 [==============================] - 3s 465us/step - loss: 0.3471 - acc: 0.8617
Epoch 18/20
6300/6300 [==============================] - 3s 504us/step - loss: 0.3462 - acc: 0.8619
Epoch 19/20
6300/6300 [==============================] - 3s 450us/step - loss: 0.3453 - acc: 0.8610
Epoch 20/20
6300/6300 [==============================] - 3s 469us/step - loss: 0.3445 - acc: 0.8605
Epoch 1/20
6300/6300 [==============================] - 8s 1ms/step - loss: 0.5766 - acc: 0.7973
Epoch 2/20
6300/6300 [==============================] - 3s 547us/step - loss: 0.4454 - acc: 0.7973
Epoch 3/20
6300/6300 [==============================] - 4s 617us/step - loss: 0.4349 - acc: 0.7973
Epoch 4/20
6300/6300 [==============================] - 4s 572us/step - loss: 0.4306 - acc: 0.7973
Epoch 5/20
6300/63

6300/6300 [==============================] - 3s 426us/step - loss: 0.4231 - acc: 0.7995
Epoch 8/10
6300/6300 [==============================] - 3s 418us/step - loss: 0.4218 - acc: 0.7995
Epoch 9/10
6300/6300 [==============================] - 3s 398us/step - loss: 0.4196 - acc: 0.7995
Epoch 10/10
6300/6300 [==============================] - 2s 375us/step - loss: 0.4180 - acc: 0.7995
Epoch 1/10
6300/6300 [==============================] - 9s 1ms/step - loss: 0.5851 - acc: 0.8000
Epoch 2/10
6300/6300 [==============================] - 3s 409us/step - loss: 0.4365 - acc: 0.8000
Epoch 3/10
6300/6300 [==============================] - 3s 492us/step - loss: 0.4288 - acc: 0.8000
Epoch 4/10
6300/6300 [==============================] - 3s 471us/step - loss: 0.4260 - acc: 0.8000
Epoch 5/10
6300/6300 [==============================] - 3s 475us/step - loss: 0.4234 - acc: 0.8000
Epoch 6/10
6300/6300 [==============================] - 3s 523us/step - loss: 0.4211 - acc: 0.8000
Epoch 7/10
6300/6300 [

Epoch 10/10
6300/6300 [==============================] - 3s 397us/step - loss: 0.4218 - acc: 0.8090
Epoch 1/10
6300/6300 [==============================] - 9s 1ms/step - loss: 0.6260 - acc: 0.7941
Epoch 2/10
6300/6300 [==============================] - 3s 411us/step - loss: 0.4714 - acc: 0.7944
Epoch 3/10
6300/6300 [==============================] - 2s 298us/step - loss: 0.4383 - acc: 0.7944
Epoch 4/10
6300/6300 [==============================] - 2s 366us/step - loss: 0.4311 - acc: 0.7944
Epoch 5/10
6300/6300 [==============================] - 3s 397us/step - loss: 0.4283 - acc: 0.7952
Epoch 6/10
6300/6300 [==============================] - 2s 304us/step - loss: 0.4261 - acc: 0.8095
Epoch 7/10
6300/6300 [==============================] - 2s 324us/step - loss: 0.4242 - acc: 0.8181
Epoch 8/10
6300/6300 [==============================] - 3s 423us/step - loss: 0.4222 - acc: 0.8206
Epoch 9/10
6300/6300 [==============================] - 3s 505us/step - loss: 0.4201 - acc: 0.8219
Epoch 10/10

6300/6300 [==============================] - 3s 458us/step - loss: 0.4392 - acc: 0.7971
Epoch 3/20
6300/6300 [==============================] - 3s 463us/step - loss: 0.4326 - acc: 0.7971
Epoch 4/20
6300/6300 [==============================] - 3s 447us/step - loss: 0.4301 - acc: 0.7971
Epoch 5/20
6300/6300 [==============================] - 3s 555us/step - loss: 0.4281 - acc: 0.7971
Epoch 6/20
6300/6300 [==============================] - 3s 487us/step - loss: 0.4262 - acc: 0.7971
Epoch 7/20
6300/6300 [==============================] - 3s 487us/step - loss: 0.4244 - acc: 0.7971
Epoch 8/20
6300/6300 [==============================] - 3s 493us/step - loss: 0.4226 - acc: 0.7971
Epoch 9/20
6300/6300 [==============================] - 3s 437us/step - loss: 0.4207 - acc: 0.8029
Epoch 10/20
6300/6300 [==============================] - 4s 560us/step - loss: 0.4198 - acc: 0.8194
Epoch 11/20
6300/6300 [==============================] - 3s 502us/step - loss: 0.4185 - acc: 0.8214
Epoch 12/20
6300/63

6300/6300 [==============================] - 3s 523us/step - loss: 0.4261 - acc: 0.7995
Epoch 5/20
6300/6300 [==============================] - 4s 575us/step - loss: 0.4237 - acc: 0.7995
Epoch 6/20
6300/6300 [==============================] - 3s 475us/step - loss: 0.4204 - acc: 0.7995
Epoch 7/20
6300/6300 [==============================] - 3s 544us/step - loss: 0.4175 - acc: 0.8151
Epoch 8/20
6300/6300 [==============================] - 3s 483us/step - loss: 0.4145 - acc: 0.8257
Epoch 9/20
6300/6300 [==============================] - 3s 491us/step - loss: 0.4120 - acc: 0.8297
Epoch 10/20
6300/6300 [==============================] - 4s 560us/step - loss: 0.4098 - acc: 0.8297
Epoch 11/20
6300/6300 [==============================] - 3s 487us/step - loss: 0.4081 - acc: 0.8311
Epoch 12/20
6300/6300 [==============================] - 4s 600us/step - loss: 0.4066 - acc: 0.8348
Epoch 13/20
6300/6300 [==============================] - 3s 485us/step - loss: 0.4051 - acc: 0.8335
Epoch 14/20
6300/

6300/6300 [==============================] - 3s 480us/step - loss: 0.4268 - acc: 0.7973
Epoch 7/20
6300/6300 [==============================] - 4s 587us/step - loss: 0.4255 - acc: 0.7973
Epoch 8/20
6300/6300 [==============================] - 3s 537us/step - loss: 0.4230 - acc: 0.7973
Epoch 9/20
6300/6300 [==============================] - 4s 567us/step - loss: 0.4210 - acc: 0.7995
Epoch 10/20
6300/6300 [==============================] - 4s 653us/step - loss: 0.4196 - acc: 0.8184
Epoch 11/20
6300/6300 [==============================] - 4s 562us/step - loss: 0.4183 - acc: 0.8200
Epoch 12/20
6300/6300 [==============================] - 3s 493us/step - loss: 0.4175 - acc: 0.8241
Epoch 13/20
6300/6300 [==============================] - 3s 536us/step - loss: 0.4166 - acc: 0.8268
Epoch 14/20
6300/6300 [==============================] - 4s 584us/step - loss: 0.4157 - acc: 0.8273
Epoch 15/20
6300/6300 [==============================] - 3s 444us/step - loss: 0.4149 - acc: 0.8284
Epoch 16/20
630

6300/6300 [==============================] - 3s 418us/step - loss: 0.4207 - acc: 0.8179
Epoch 9/20
6300/6300 [==============================] - 3s 498us/step - loss: 0.4183 - acc: 0.8241
Epoch 10/20
6300/6300 [==============================] - 4s 575us/step - loss: 0.4164 - acc: 0.8270
Epoch 11/20
6300/6300 [==============================] - 3s 522us/step - loss: 0.4147 - acc: 0.8286
Epoch 12/20
6300/6300 [==============================] - 3s 468us/step - loss: 0.4131 - acc: 0.8297
Epoch 13/20
6300/6300 [==============================] - 3s 499us/step - loss: 0.4121 - acc: 0.8317
Epoch 14/20
6300/6300 [==============================] - 3s 498us/step - loss: 0.4108 - acc: 0.8322
Epoch 15/20
6300/6300 [==============================] - 4s 571us/step - loss: 0.4101 - acc: 0.8321
Epoch 16/20
6300/6300 [==============================] - 4s 569us/step - loss: 0.4090 - acc: 0.8322
Epoch 17/20
6300/6300 [==============================] - 3s 499us/step - loss: 0.4081 - acc: 0.8327
Epoch 18/20
6

6300/6300 [==============================] - 3s 429us/step - loss: 0.4186 - acc: 0.7976
Epoch 11/20
6300/6300 [==============================] - 5s 870us/step - loss: 0.4170 - acc: 0.8056
Epoch 12/20
6300/6300 [==============================] - 3s 502us/step - loss: 0.4157 - acc: 0.8211
Epoch 13/20
6300/6300 [==============================] - 3s 547us/step - loss: 0.4148 - acc: 0.8237
Epoch 14/20
6300/6300 [==============================] - 3s 511us/step - loss: 0.4137 - acc: 0.8262
Epoch 15/20
6300/6300 [==============================] - 3s 499us/step - loss: 0.4127 - acc: 0.8287
Epoch 16/20
6300/6300 [==============================] - 3s 523us/step - loss: 0.4119 - acc: 0.8283
Epoch 17/20
6300/6300 [==============================] - 3s 487us/step - loss: 0.4109 - acc: 0.8297
Epoch 18/20
6300/6300 [==============================] - 3s 489us/step - loss: 0.4104 - acc: 0.8316
Epoch 19/20
6300/6300 [==============================] - 3s 456us/step - loss: 0.4093 - acc: 0.8338
Epoch 20/20


In [35]:
best_parameters=grid_search.best_params_
best_parameters
#it will find best parameters amomg all the parameters....

{'batch_size': 25, 'epochs': 20, 'optimizer': 'rmsprop'}

In [38]:
best_score=grid_search.best_score_
best_score
# it will find best score among all the scores or accuracy...

0.8342857142857143